### PR TITLE
Add point intersection calls

### PR DESCRIPTION
**Pull request by Zeitsperre**

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@huard I'll need to make a few adjustments in the RavenWPS code, but everything is working as expected. Nicely done!

**Review by huard — APPROVED** [review]
Excellent !

**Comment by huard** [comment]
@Zeitsperre Any idea why the conda build has errors ?

**Comment by Zeitsperre** [comment]
Not yet, but I'm gearing up to look into that this morning, though it's a nice surprise to see that the PyPI-only builds are working as expected. Will post updates on slack.

**Pull request merged**
