### PR TITLE
Fix problem with netCDF file caching

### PR DESCRIPTION
**Pull request by cjauvin**
This is a possible fix for https://github.com/CSHS-CWRA/RavenPy/issues/4. In order to use the `with` statement, I'm using a generator, which I renamed to `hydrographs`, and introduced an additional `hydrograph` property, in order to keep the tests `test_emulators.py::TestGR4JCN` from crashing. As is, this fixes the problem we had with `test_overwrite` and `xarray==0.16.1`.

Note that this PR is just intended as a discussion, as I'm really not sure that this is the solution we want/need in this context. Also, whatever the solution we adopt, it will need to be expanded to the other uses of netCDF files throughout the project, to be consistent.

### CODE REVIEW

**Review by huard — COMMENTED** [review]
Elegant, but I'm wondering when exactly is the file closed ?

**Comment by cjauvin** [comment]
> Elegant, but I'm wondering when exactly is the file closed ?

The `__exit__` method of the context manager is called at every iteration of the for loop, and thus every time `next()` is called on the generator. So the result I believe is a collection (or singleton) of properly closed file handles.

**Comment by huard** [comment]
But when you `get` the property, don't you create an other generator object, so the `next` is called not on the first object, but on the second object ?

**Comment by cjauvin** [comment]
My understanding that accessing the property is simply refering to the generator itself (i.e. the property/method _is_ the generator) and that while you haven't "done" anything with it, no file is either open or close (because no `yield` has been executed yet). But I will verify to make sure.

**Comment by cjauvin** [comment]
@david:

``` python
class Ressource:
    def __init__(self, i):
        self.i = i
        print(f"init {self.i}")

    def __enter__(self):
        print(f"enter {self.i}")
        return self.i

    def __exit__(self, *exc):
        print(f"exit {self.i}")


class User:
    @property
    def ressources(self):
        for i in range(3):
            with Ressource(i) as r:
                yield r


u = User()
rs = [r for r in u.ressources]

# init 0
# enter 0
# exit 0
# init 1
# enter 1
# exit 1
# init 2
# enter 2
# exit 2
```

**Comment by huard** [comment]
But then I assume that `close` is called, so how can we access the content then ? There may be some xarray cache magic here.

**Comment by cjauvin** [comment]
I have no idea, and it might be why this solution is not really appropriate actually.

**Comment by huard** [comment]
I suggest we merge this and see how it goes.

**Comment by huard** [comment]
Should we merge this ? Seems we're having problems with caching.

**Comment by cjauvin** [comment]
This is for `hydrographs` only, do you think this is the only one causing issue? If not this trick should be repeated elsewhere to be consistent.

**Comment by huard** [comment]
Same trick should be applied to storage as well.

**Comment by cjauvin** [comment]
I think it's better to close this as too much time has passed and I'm not sure the issue is up to date anymore.

**Pull request closed without merging**
