### PR TITLE
Update Fiona to v1.9

### PR DESCRIPTION
**Pull request by Zeitsperre**
Fiona v1.9 has API changes that necessitate changes on our end. This will render us more in line with Fiona v2.0 when it is soon released. The primary change is that Fiona features are now their own class `fiona.Feature` containing `fiona.Geometry` classes. These are compatible with `dict()` outputs, so no changes should be needed in `Raven-WPS`.

For more information, see: https://github.com/Toblerity/Fiona/pull/787

### Changes

- Set minimum GDAL version at 3.1
- `pip` was comparing compatible versions of `sphinx_rtd_theme`, so this has now been set a `>=1.0`.
- The new Fiona API is now used for vector reprojection. `Fiona.write` is now used for writing output file JSONs.

### Additonal Notes
~The conda package is not yet released due to a few small changes needed in their testing suite. This should be addressed soon. See: https://github.com/conda-forge/fiona-feedstock/pull/208~ - This has been released on conda-forge.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@huard 

The present failures are due to service issues with our THREDDS server. Should I make these tests `XFAIL`able?

**Comment by huard** [comment]
The error I'm seeing has to do with cf-xarray:
```No such file or directory: '/home/runner/work/RavenPy/RavenPy/.tox/py38/lib/python3.8/site-packages/cf_xarray/data/cf-standard-name-table.xml'```

**Comment by Zeitsperre** [comment]
The THREDDS issues have been resolved, cf-xarray fixes are on the way: https://github.com/xarray-contrib/cf-xarray/issues/415

I'm wondering though if we should allow the THREDDS-related tests to fail since they're service-dependent. What do you think?

**Comment by huard** [comment]
Is there a way to fail only if the service is not on ? If the service is available, but the test fails, I'd like to catch that.

**Comment by Zeitsperre** [comment]
I can definitely look into that. If it's simple enough that I can add it here this morning, I'll add it. Otherwise, no more changes. As it stands, though, am I good to merge?

**Review by huard — APPROVED** [review]

**Comment by Zeitsperre** [comment]
Failing because of a new `black`. Opening another PR to fix this...

**Pull request merged**
