### PR TITLE
Custom output

### PR DESCRIPTION
**Pull request by Idajab**
The custom output command is added. 
The reservoir command is modified to simulate the Lake in HBV-EC model. 
The LakeStorage is modified from Slow_Reservoir to use Lake_Storage compartment to have consistency with HBV-EC model. 
The :WriteForcingFunctions is added to .rvi.
The soil profiles are modified for the SLSO region.
The .rvc file is modified to create an empty file, due to issues related to the Raven Warnings.

### CODE REVIEW

**Comment by Idajab** [comment]
The custom output command is added.
The reservoir command is modified to simulate the Lake in HBV-EC model.
The LakeStorage is modified from Slow_Reservoir to use Lake_Storage compartment to have consistency with HBV-EC model.
The :WriteForcingFunctions is added to .rvi.
The soil profiles are modified for the SLSO region.
The .rvc file is modified to create an empty file, due to issues related to the Raven Warnings.

**Comment by huard** [comment]
@Idajab There are two version of hbvecmod in this pr. Which one do you use?

**Comment by Idajab** [comment]
> @Idajab There are two version of hbvecmod in this pr. Which one do you use?

I use the hbvecmod in RavenPy-aida-famine/ravenpy/models/emulators/.

**Comment by huard** [comment]
Integrated in the wider refactoring.

**Pull request closed without merging**
