### PR TITLE
Do not write rv zip file and merge outputs if suppress_output is True

### PR DESCRIPTION
**Pull request by huard**
Seems to solve the non-linear slow-down described in #181

### CODE REVIEW

**Comment by huard** [comment]
Shoud resolve https://github.com/Ouranosinc/raven/issues/168

**Comment by huard** [comment]
Do we want to create the zip file from scratch, instead of append to it ?

**Comment by richardarsenault** [comment]
I am not sure! In some cases it might be useful to have a log of what all results are, in which case we set suppress_output to false. For most cases it will be a single run, and for most calibrations we won't need them at all. So I think the proposed solution here is the best of all worlds.

**Review by richardarsenault — APPROVED** [review]
Works perfectly, suggest we merge this so we can merge spotpy and then upgrade notebooks at a later time.

**Comment by huard** [comment]
Sorry, didn't get notified of your comment. Will do. 
Everyone is gone, so I'll take care of the nb next week.

**Comment by richardarsenault** [comment]
@huard Hmmm one thing we could do (and that I do in my notebooks) is that at the end of the calibration, re-do a simulation with all the same data and optimal parameters but with suppress_output = False. Could we simply hardcode that, and return the diagnostics along with the original outputs of the calibration method?

**Comment by huard** [comment]
That would work, but from a user point of view, you would set suppress_output to True, then after calling the model, you'd end up with suppress_output being False. I think this solution is ok as long as it is contained with the WPS service, but I would not do that in RavenPy.

**Pull request merged**
