### PR TITLE
unpin climpred

### PR DESCRIPTION
**Pull request by huard**

### CODE REVIEW

**Review by Zeitsperre — APPROVED** [review]
LGTM

**Comment by huard** [comment]
@Zeitsperre Any idea why test_get_raster_wcs would fail?

**Comment by Zeitsperre** [comment]
No. The code has been untouched for 6+ months. Most dependencies are not any newer. That's really strange. I'll trigger a new build and if it fails again I'll see if I can track it down.

**Comment by Zeitsperre** [comment]
pyproj 3.2.0 was recently released. I'll see if something really broke our tests from there.

**Comment by Zeitsperre** [comment]
I finally managed to reproduce this locally. Looks like the new pyproj or rasterio are the culprits. Will look into this in the coming days. The workaround is to pin those below their most recent versions for now.

**Comment by huard** [comment]
pyproj is not responsible. 
The error shows up in rasterio 1.2.7. 
rasterio 1.2.6 works fine with pyproj 3.2.0

**Pull request merged**
