### PR TITLE
Initial migration from raven repo

### PR DESCRIPTION
**Pull request by cjauvin**

### CODE REVIEW

**Review by huard — CHANGES_REQUESTED** [review]
Darn, I forgot that we wanted to keep large test data files outside of the repo...

Ideas ?

**Comment by cjauvin** [comment]
> Darn, I forgot that we wanted to keep large test data files outside of the repo...
> Ideas ?

We could include them as an optional extra package maybe?

**Comment by Zeitsperre** [comment]
@cjauvin There's already some discussion about this. I'll likely be creating a tesdata repo for Raven(Py) later today.

**Comment by Zeitsperre** [comment]
For more information: https://github.com/Ouranosinc/raven/issues/318

**Comment by tlvu** [comment]
> > Darn, I forgot that we wanted to keep large test data files outside of the repo...
> > Ideas ?
> 
> We could include them as an optional extra package maybe?

FYI, the commit that has those large testdata should be destroyed and recreated.  Just commit again to delete those large testdata file will still keep them in the history and bloat the repo size.

**Comment by cjauvin** [comment]
yes absolutely, good idea, will do!

**Comment by cjauvin** [comment]
Actually I think that this commit crashed my text editor (Emacs).. 😟

**Comment by cjauvin** [comment]
I removed the `tests/testdata` folder from my previous commit and force-pushed the change.

**Review by huard — APPROVED** [review]

**Pull request merged**
